services:
  db:
    image: postgis/postgis:13-3.1
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    networks:
      - app-network

  ram:
    image: redis:alpine
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env # This will load environment variables from .env file
    command: >
      sh -c "python /app/resc/manage.py migrate &&
            python /app/resc/manage.py init_admin &&
            daphne -b 0.0.0.0 -p 8000 resc.asgi:application"
    volumes:
      - .:/app
    # ports:
    #   - "8000:8000"
    depends_on:
      - db
      - ram
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./resc/staticfiles:/app/resc/staticfiles
      # - static_volume:/app/resc/staticfiles/
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

volumes:
  pgdata:
    external: true
  static_volume:
    external: true

networks:
  app-network:
    external: true
