# Generated by Django 5.0.2 on 2024-03-30 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'NORMAL'), (2, 'EMERGENCY_CENTER'), (3, 'SUPER')], default=1, verbose_name='Type')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone number')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('postal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ('created',),
            },
        ),
    ]
