# Generated by Django 5.0.4 on 2024-08-04 10:39

import agents.utils
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location')),
            ],
            options={
                'verbose_name': 'Point',
                'verbose_name_plural': 'Points',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='polygon')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('busy', models.BooleanField(default=False, verbose_name='Agent is busy')),
                ('emergency_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='AgentDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('api_key', models.CharField(blank=True, default=agents.utils.generate_api_key, max_length=100, verbose_name='API Key')),
                ('name', models.CharField(max_length=100, verbose_name='Device name')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='agents.agent', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Agent device',
                'verbose_name_plural': 'Agent devices',
                'ordering': ('created',),
                'unique_together': {('agent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AgentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('data', agents.utils.CustomJSONField(default=list)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='agents.agentdevice', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Agent Record',
                'verbose_name_plural': 'Agent Records',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'JUST_DEFINED'), (2, 'IN_PROGRESS'), (3, 'SUCCESS'), (4, 'FAILURE')], default=1, verbose_name='Status')),
                ('archived', models.BooleanField(default=False, verbose_name='Mission is archived')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='agents.agent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to=settings.AUTH_USER_MODEL, verbose_name='Alive subject')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='SubjectDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('api_key', models.CharField(blank=True, default=agents.utils.generate_api_key, max_length=100, verbose_name='API Key')),
                ('name', models.CharField(max_length=100, verbose_name='Device name')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Subject device',
                'verbose_name_plural': 'Subject devices',
                'ordering': ('created',),
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SubjectRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('data', agents.utils.CustomJSONField(default=list)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='agents.subjectdevice', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Subject Record',
                'verbose_name_plural': 'Subject Records',
                'ordering': ('created',),
            },
        ),
    ]
