# Generated by Django 5.0.2 on 2024-03-31 19:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='polygon')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='point',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='location'),
        ),
    ]
