# Generated by Django 5.0.4 on 2024-10-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdevice',
            name='occupied',
            field=models.BooleanField(default=False, verbose_name='Subject is occupied'),
        ),
    ]
